GET http://localhost:3001/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJpYXQiOjE2Nzk3ODY3ODksImV4cCI6MTY3OTc4Njg0OX0.015a3spgSYEgktMo6IrnITuyIsyMcnmphfZ85uf9OA0

###
GET http://localhost:3001/products/2

###
PATCH  http://localhost:3001/products/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJpYXQiOjE2Nzk3ODY3NDgsImV4cCI6MTY3OTc4NjgwOH0.l9exy9q2q8pLQs82qBrmORoiuNSEFiJCE5FQyiGGNcE

{
    "name": "Silvaant"
}


###
POST http://localhost:3001/products/add
Content-Type: application/json

{
    "name": "Silvant",
    "price": 1024.00,
    "quantity": 250,
    "pillShape": "ground",
    "description": "Very expensive meds!",
    "prescription": 1,
    "expirationDate": "2023-12-31",
    "supply": 10
}

###
DELETE http://localhost:3001/products/29
Authorization: Bearer