###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "alex",
    "password": "luca"
}

###
POST http://localhost:3001/users/signup
Content-Type: application/json

{
    "username": "alexluca",
    "password": "1234adasAsd.5",
    "firstName": "Alex",
    "lastName": "Luca",
    "cnp": "1990406046288",
    "phone": "+40 743 568 097",
    "email": "alex@luca.com",
    "address": "Bucuresti, Romania"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXhsdWNhIiwiaWF0IjoxNjc5NzYzMTQ4fQ.W8BdlGQ3RGcmlXUkbmxauDe2NFSInumlDxRAGOpoiRw"
}
###
DELETE http://localhost:4000/logout
Content-Type: application/json

###
GET http://localhost:3001/users/

###
GET http://localhost:3001/users/alexluca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJpYXQiOjE2Nzk4MzU4MjQsImV4cCI6MTY3OTgzNTg4NH0.ijpnYxIZ52fU3TpBvH89IDcrwh3qXtc6LmFO2Tpb8Ek

###
PATCH  http://localhost:3001/users/alexluca
Content-Type: application/json
Authorization: Bearer 

{
    "firstName": "Alexandru",
    "lastName": "Lucas",

}
###
DELETE http://localhost:3001/users/anamariaaa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYW1hcmlhYWEiLCJpYXQiOjE2Nzk3NjY0NTksImV4cCI6MTY3OTc2NjUxOX0.3ohZKb5WcSVGSndSvHRE8AHtQv94XqakdEUTnxzf8_g